### ISSUE TITLE
Summer and non-summer workloads

### ISSUE THREAD

**Issue by eavesjump** [MSCSHub/MSCSHub#109]
Currently, summer workloads (hrs/wk) are treated identically to non-summer workloads. Perhaps they should be two different columns?

**Comment by EricPryzant** [comment]
Hi @eavesjump, unfortunately this would be challenging from a technical and UX standpoint. However, I think it's a good idea to help users see the difference between summer sessions and full semesters. What if we added an option to filter for summer/full term?

**Comment by eavesjump** [comment]
I think that would be great if it's not an optional filter but rather a required filter. Because without the filter the workload column is too misleading to use at all.
