### ISSUE TITLE
Bug on Courses Page

### ISSUE THREAD

**Issue by smithla02** [MSCSHub/MSCSHub#148]
I think there may be a bug on the [https://mscshub.com/courses](https://mscshub.com/courses) page? It seems not all the courses are loading [i.e. see all the blank lines in the screenshot below].

This is what the site looks like for me (I tested it on Brave and Safari).

![Screen Shot 2022-05-22 at 8 59 22 PM](https://user-images.githubusercontent.com/31872910/170104828-029d6a35-cc8e-4ca0-afc3-818b7c0e1088.png)

**Comment by estraw1059** [comment]
I am unable to recreate. Can you check again? also can you post the version of safari you are running?

**Comment by EricPryzant** [comment]
This was due to a data corruption issue related to how courses are imported automatically with a web scraper. The data was fixed in the db and now courses should appear correctly.
