### ISSUE TITLE
Course Stats not populating from reviews

### ISSUE THREAD

**Issue by sahilda** [MSCSHub/MSCSHub#149]
The QIS course is a great example where there's 5 reviews posted but the course summary data doesn't populate (https://mscshub.com/courses/Introduction%20to%20Quantum%20Information%20Science).

I see there's two collections, one for reviews and another for class, and I don't see how the reviews populates class. Is there a background service that aggregates the data?

Additionally why is there course data but no reviews for ALFAA (https://mscshub.com/courses/Advanced%20Linear%20Algebra%20for%20Computation)? This leads me to think it's intentional that the data is not the same but I'm not sure how the class data is popiulated.

**Comment by estraw1059** [comment]
I am aware of the QIS issue. There is a backend script that takes review and pushes the data into the course. I will look into why that isn't working this weekend. It most likely a typo when I created the class. (We don't have a defined process). 

The ALFAA is concerning and I will look into it. Perhaps there is a mismatch on ids that just need to be resolved.

By the end of June we hope to have the backend up on github. The repo is private right now as we are trying to ensure that we are not exposing any keys that could cause damage. 

Thanks!

**Comment by estraw1059** [comment]
It is fixed and appears to be working. Please let me know if you see any further issues
