### ISSUE TITLE
Advanced Linear Algebra is not pulling up reviews anymore despite there being 17 written for the class

### ISSUE THREAD

**Issue by EricPryzant** [MSCSHub/MSCSHub#159]
There are 17 reviews for ALA but none of them show up and the website console isn't showing any errors. The "reviews" component has no trouble pulling these reviews so there must be some bug in the code that's blocking them. 

![image](https://user-images.githubusercontent.com/54600184/175610931-1bca2b8b-e953-49c8-ac23-601bc2ebd218.png)

![image](https://user-images.githubusercontent.com/54600184/175610879-74b0e1fd-fc16-44f9-b421-cf405260dfd3.png)

**Comment by aanand3** [comment]
@EricPryzant Not sure if there was a code fix but this problem looks like it's disappeared, at least on my machine. Might be good to close it?

**Comment by estraw1059** [comment]
Closed
