### ISSUE TITLE
Default sort or at least tie break reviews by newest first

### ISSUE THREAD

**Issue by IDoCodingStuffs** [MSCSHub/MSCSHub#176]
Right now default sort is "most helpful", and ties are broken by displaying the oldest review first. Which is not very desirable since that pushes fresh reviews to the bottom.

IMO default should be newest first or at least grouped by most recent semester and groups sorted by recent, with elements sorted by votes.

**Comment by prizeant** [comment]
That shouldn’t be too hard to change.

**Comment by estraw1059** [comment]
Resolved
