### ISSUE TITLE
Change SIMPL, Virtualization and QIS subject type

### ISSUE THREAD

**Issue by sanchit3008** [MSCSHub/MSCSHub#188]
These should now have systems, systems and theory tags respectively instead of elective.

**Comment by aanand3** [comment]
@sanchit3008 I'm actually still seeing these as electives on the courses page. Did this change authoritatively? https://cdso.utexas.edu/mscs

**Comment by sanchit3008** [comment]
@aanand3 yes, there was an email about it and since then it was changed in the central edX course as well

**Comment by estraw1059** [comment]
You can change courses by hitting the edit button on the course page. Feel free to update.
