### ISSUE TITLE
New MSDS Course

### ISSUE THREAD

**Issue by Charlie-Henry** [MSCSHub/MSCSHub#195]
There's a new course that started in Spring 2024:
- Data Science for Health Discovery and Innovation: DSC 395T

It would be great to get this added ASAP as it's the end of the semester and I'm sure people are going to want to submit or see reviews on this new course.

Thanks!

**Comment by Charlie-Henry** [comment]
tagging y'all, @estraw1059 @EricPryzant. Appreciate you both

**Comment by estraw1059** [comment]
I get this up this week/this weekend. Sorry been swamped at work.

**Comment by estraw1059** [comment]
Okay it should be there for MSDS

**Comment by Charlie-Henry** [comment]
awesome, thanks!
