### ISSUE TITLE
Request for MSAIHub

### ISSUE THREAD

**Issue by ajayambre** [MSCSHub/MSCSHub#196]
I am a new student of the MSAI program and came across the MSCSHub and MSDSHUb sites which I found to be very helpful.
For someone like me who is just starting the program, the information about the courses and the reviews provided are extremely useful and will benefit me in navigating this program.

There are a few courses in the MSAI program like Ethics in AI, AI in Healthcare that are unique to the MSAI program and there may be more such in future.

It would be great if we can have a dedicated MSAIHub site where these courses and maybe some future ones can go and the other common courses can be inherited from the MSCS and MSDS sites.

I have experience working with Angular and I am willing to contribute.
Thanks for your great work on the MSCSHub and MSDSHub and hope you consider this request for a dedicated MSAIHub!

**Comment by bdharris08** [comment]
Came here looking for this as well. Although I think that it would be cool to have a separate MSAI hub site, it may make more sense to just modify this site to include AI track courses. However, it doesn't look like anyone is maintaining this, there are a ton of open issues and pull requests :(
Maybe there's a path forward via forking and sourcing reviews from the same backend, but I haven't looked into the code far enough to see if that's possible.

**Comment by estraw1059** [comment]
MSCS and MSDS use the same back end. Sadly that is the larger lift for setting up a new site and the code is still private as the keys to all the backend code was never hidden properly. Ill try to take a look as this is something we have wanted to do (We own the domain name) but the original code owners (myself included) have been quite busy lately. 

I put this down as something to play catch-up on in the next 2 months so I will see what i can do . I am going to leave this open as it should be fixed.

**Comment by bdharris08** [comment]
Hi Eric, thanks for replying. I'm sorry to imply that you aren't responsive, I know maintaining this repo is probably a thankless task, so thank you for taking time out of your busy schedule! 

The hub is already useful to me as I plan my MSAI course load, but for a couple of small changes:
- Add missing AI track specific courses (Ethics in AI, AI in Healthcare)
- Add "MS AI" to "Filter by category" section

Here's the course info: https://cdso.utexas.edu/msai

I'll try to dig into the code this week and see if I can't submit an PR for those changes.

**Comment by estraw1059** [comment]
I have everything upgraded in regards to angular, I also think I have msai working locally. I am going through courses this week to get the backend up to date. Then I will work on getting that deployed out

**Comment by estraw1059** [comment]
Okay all courses are on the website and they are on msaihub.com

I am going to mark this as closed, if you have a discord or reddit page that should be linked to instead (I think it currently links to the MSDS please reopen/open a new issue with the ticket. I am out of the loop on that Course.
