### ISSUE TITLE
Add tooltips to language chips on course details

### ISSUE THREAD

**Issue by EricPryzant** [MSCSHub/MSCSHub#21]
It would be nice to add tooltips to the language chips that show up on the course details page.

**Comment by EricPryzant** [comment]
The best approach is probably to convert the languages array to a map. It's going to be tougher to dynamically create textboxes that can handle it but it should be doable without too much fuss.

**Comment by EricPryzant** [comment]
![image](https://user-images.githubusercontent.com/54600184/114612662-0804db80-9c68-11eb-9ee4-3ce58dae5473.png)

**Comment by estraw1059** [comment]
Too much of a re-write closing for now
