### ISSUE TITLE
Can no longer sort on the Reviews, Rating, Difficulty, Workload (hrs/wk), or Textbook on the Course Tab

### ISSUE THREAD

**Issue by mahir1701** [MSCSHub/MSCSHub#222]
<img width="1373" alt="image" src="https://github.com/user-attachments/assets/74072caf-59e4-48d9-b978-338d7ddd53d3">
Used to be arrows allowing user to sort by ascending or descending order

**Comment by estraw1059** [comment]
Good note, must have been lost during the version updates. I will take a look at this this week.
