### ISSUE TITLE
User Profile - First Name, Last Name, First Semester Showing "null"

### ISSUE THREAD

**Issue by 12wollmana** [MSCSHub/MSCSHub#80]
When viewing the user profile page, my first name, last name, and first semester are all showing as null (see screenshot).  

I know that I've filled out this information on sign up.  Editing my information does not fix this issue.

![image](https://user-images.githubusercontent.com/2817506/115970519-72d7d180-a508-11eb-8b49-fa9255be2689.png)

**Comment by EricPryzant** [comment]
Thanks for letting us know! We'll get right on it

**Comment by EricPryzant** [comment]
@12wollmana The root cause was identified and fixed. @estraw1059 is currently updating the database to resolve the issue for all users that were affected. You should see it fixed on your end soon

**Comment by estraw1059** [comment]
Should be fixed. Please confirm @12wollmana

**Comment by 12wollmana** [comment]
Issue has been fixed on my end, thanks!
