### ISSUE TITLE
MSDSHub links to MSCSHub for feedback/suggestions 

### ISSUE THREAD

**Issue by piggjf** [MSCSHub/MSCSHub#99]
I just realized MSDSHub has its own github.  So let's change this to a bug report.  msdshub.com directs us here for feedback/suggestions.

**Comment by EricPryzant** [comment]
@piggjf Thanks for making a issue about this. However, this is not a mistake. Both websites operate off of the same code base, which makes it much much easier to maintain and took a bit of ingenuity or design with great success. We use Github sites to host MSCSHub and MSDSHub straight from a github repositority. However, we can't connect one repo to two domains so instead we mirror the active website code to the MSDS repo and use that solely for hosting the website. The master repository lives here at MSCSHub.
